(source gnu)
(source melpa)
;; Add repository
(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; Add packages
(depends-on "auto-complete")
(depends-on "helm")
(depends-on "ctable")
(depends-on "yatex")
(depends-on "css")
(depends-on "python-mode")
(depends-on "markdown-mode")
(depends-on "stan-mode")
(depends-on "ein")
(depends-on "yatemplate")
(depends-on "py-autopep8")
(depends-on "elpy")
(depends-on "afternoon-theme")
(depends-on "flymake-cursor")
(depends-on "flymake-easy")
(depends-on "flymake-python-pyflakes")
(depends-on "recentf-ext")
(depends-on "elscreen")
(depends-on "polymode")
(depends-on "color-theme")


;; Add packages on GitHub
;(depends-on "auto-complete-acr":git " https://github.com/myuhe/auto-complete-acr.git")
;(depends-on "ess-R-data-view":git "https://github.com/myuhe/ess-R-data-view.git")
;(depends-on "e2wm-R":git "https://github.com/myuhe/e2wm-R.git")
;(depends-on "emacs-window-layout":git "https://github.com/kiwanami/emacs-window-layout.git")
;(depends-on "emacs-window-manager":git "https://github.com/kiwanami/emacs-window-manager")
;(depends-on "inlineR":git "https://github.com/kiwanami/emacs-window-manager.git")
